#!/bin/bash

while [ "$1" != "" ]; do
  case $1 in
    --conf-dir )
      shift
      conf_dir=$1
      ;;
    --ssh-dir )
      shift
      ssh_dir=$1
      ;;
    --region )
      shift
      region=$1
      ;;
    *)
      cmd=$1
      ;;
  esac
  shift
done

echo $conf_dir

if [ -z "$conf_dir" ]; then
  echo "Missng configuration directory"
  echo "Syntax ./terraform --conf-dir [dir] cmd"
  exit 1
fi


if [ -z "$ssh_dir" ]; then
  ssh_dir=$conf_dir
fi

if [ -z "$cmd"  ]; then
  echo "Missng terraform command"
  echo "Syntax ./terraform --conf-dir [dir] cmd"
  exit 1
fi

IMAGE=terraform-cli:v1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z $(docker images --format "table {{.Repository}}:{{.Tag}}" | grep $IMAGE) ]; then
  echo "Building docker image"
  test=$(docker build -t $IMAGE $DIR 2>&1)
  if [ $? -ne 0 ]; then
    echo "Failed to build supporting container"
    exit 1
  fi
fi

TARGET_CONF_DIR="/var/terraform"
TARGET_SSH_DIR="/root/.ssh"

docker run --rm --name terraform-cli \
  -v $conf_dir:$TARGET_CONF_DIR \
  -v $ssh_dir:$TARGET_SSH_DIR \
  -e OS_REGION_NAME=$region \
  $IMAGE $cmd
