#!/bin/bash

while [ "$1" != "" ]; do
  case $1 in
    --auth-url )
      shift
      auth_url=$1
      ;;
    --region-name )
      shift
      region_name=$1
      ;;
    --tenant-id )
      shift
      tenant_id=$1
      ;;
    --tenant-name )
      shift
      tenant_name=$1
      ;;
    -u | --username )
      shift
      username=$1
      ;;
    -p | --password )
      shift
      password=$1
      ;;
  esac
  shift
done

IMAGE=openstack-cli:v1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
image=$(docker images --format "table {{.Repository}}:{{.Tag}}" | grep $IMAGE)

if [ -z "$image" ]; then 
  echo "Building docker image"
  test=$(docker build -t $IMAGE $DIR 2>&1)
  if [ $? -ne 0 ]; then
    echo "Failed to build supporting container"
  fi
fi

docker run --rm -it --name openstack-cli \
-e "OS_AUTH_URL=$auth_url" \
-e "OS_REGION_NAME=$region_name" \
-e "OS_TENANT_ID=$tenant_id" \
-e "OS_TENANT_NAME=$tenant_name" \
-e "OS_USERNAME=$username" \
-e "OS_PASSWORD=$password" \
--entrypoint openstack \
$IMAGE $*
